version: "3"
services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_DB=onlinejudge
            - POSTGRES_PASSWORD=password
    
    backend:
        build: .
        container_name: onlinejudge
        restart: always
        depends_on: 
            - postgres
        links:
            - postgres
        environment: 
            - DATABASE_URL=postgresql://postgres:password@postgres/postgres
        ports:
            - 5000:5000