version: "3"
services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_DB=onlinejudge
            - POSTGRES_PASSWORD=password
        networks:
            - staoj
    
    backend:
        build: .
        container_name: onlinejudge
        restart: always
        depends_on: 
            - postgres
        links:
            - postgres
        environment: 
            - DATABASE_URL=postgresql://postgres:password@postgres/postgres
        ports:
            - 5000:5000
        networks:
            - staoj
    
    nginx:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes:
            - /etc/nginx/sites-enabled/onlinejudge:/etc/nginx/sites-enabled/onlinejudge
        ports:
            - "80:80"
            - "443:443"
        networks:
            - staoj

networks:
    staoj:
        driver: bridge