"""empty message

Revision ID: 87c1eedc33aa
Revises: 67e8d8b3ef8f
Create Date: 2020-01-04 16:55:44.013080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c1eedc33aa'
down_revision = '67e8d8b3ef8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'title')
    # ### end Alembic commands ###
